package com.crayons_2_0.mockup;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Benutzeransicht extends VerticalLayout {
    protected TabSheet kurs11;
    protected TabSheet kurs112;
    protected TabSheet kurs1121;
    protected TabSheet kurs113;
    protected TabSheet kurs12;
    protected TabSheet kurs13;
    protected TabSheet kurs14;

    public Benutzeransicht() {
        Design.read(this);
    }
}
